# Generated by Django 4.1.4 on 2023-01-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=20)),
                ('user_create_date', models.DateTimeField()),
            ],
        ),
    ]
